[tools]
# =================================================================================================
# CI Tools
# =================================================================================================
"aqua:rhysd/actionlint" = "latest"
